-- Secure live tracking for Career and Campus Ambassador applications.
-- Run this once in the DevQuest Supabase SQL editor.

create table if not exists public.applications (
  id uuid primary key default gen_random_uuid(),
  submission_id uuid not null unique,
  application_type text not null check (application_type in ('career', 'ambassador')),
  tracking_code text not null unique,
  access_token_hash text not null unique check (char_length(access_token_hash) = 64),
  full_name text not null check (char_length(full_name) between 2 and 120),
  email text not null,
  phone text,
  city text,
  position text,
  details jsonb not null default '{}'::jsonb,
  cv_filename text,
  status text not null default 'submitted' check (status in ('submitted', 'under_review', 'shortlisted', 'interview', 'accepted', 'rejected')),
  public_note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  status_updated_at timestamptz not null default now()
);

create index if not exists applications_status_created_idx on public.applications(status, created_at desc);
create index if not exists applications_type_created_idx on public.applications(application_type, created_at desc);
create index if not exists applications_email_idx on public.applications(lower(email));

alter table public.applications enable row level security;

-- No public table policies are created. Public status requests are validated by
-- a server route using the SHA-256 hash of an unguessable 256-bit token.

create table if not exists public.application_status_history (
  id bigint generated by default as identity primary key,
  application_id uuid not null references public.applications(id) on delete cascade,
  status text not null check (status in ('submitted', 'under_review', 'shortlisted', 'interview', 'accepted', 'rejected')),
  public_note text,
  changed_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create index if not exists application_status_history_application_idx
on public.application_status_history(application_id, created_at asc);

alter table public.application_status_history enable row level security;

create or replace function public.set_application_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  if new.status is distinct from old.status then
    new.status_updated_at = now();
  end if;
  return new;
end;
$$;

drop trigger if exists set_application_updated_at on public.applications;
create trigger set_application_updated_at
before update on public.applications
for each row execute procedure public.set_application_updated_at();
