"use client";

import { FormEvent, useEffect, useState } from "react";
import { createClient, type SupabaseClient, type User } from "@supabase/supabase-js";
import { AlertCircle, ArrowUpRight, CheckCircle2, LoaderCircle, LockKeyhole, LogIn, LogOut, Mail, ShieldCheck, UserPlus, UserRound, X } from "lucide-react";

let browserClient: SupabaseClient | null | undefined;
function getSupabase() {
  if (browserClient !== undefined) return browserClient;
  const url = process.env.NEXT_PUBLIC_SUPABASE_URL;
  const key = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;
  browserClient = url && key ? createClient(url, key, { auth: { persistSession: true, autoRefreshToken: true, detectSessionInUrl: true } }) : null;
  return browserClient;
}

export function ContactForm({ compact = false }: { compact?: boolean }) {
  const [sent, setSent] = useState(false);
  function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); const data = new FormData(event.currentTarget); const name = String(data.get("name") || ""); const email = String(data.get("email") || ""); const scope = String(data.get("scope") || "General enquiry");
    setSent(true); window.location.href = `mailto:devquestpk@gmail.com?subject=${encodeURIComponent(`DevQuest enquiry from ${name}`)}&body=${encodeURIComponent(`Name: ${name}\nEmail: ${email}\n\nProject / message:\n${scope}`)}`;
  }
  return <form className={`contact-form ${compact ? "contact-form-compact" : ""}`} onSubmit={submit}>{!compact && <span className="form-icon"><Mail /></span>}<p className="eyebrow">NO-OBLIGATION DISCOVERY CALL</p><h2>{compact ? "Start a conversation." : "Let’s build something meaningful."}</h2><p className="form-copy">Share a few details and we&apos;ll help you identify the clearest next step.</p><label><span>Your name</span><input name="name" required placeholder="Full name" autoComplete="name" /></label><label><span>Work email</span><input name="email" type="email" required placeholder="you@company.com" autoComplete="email" /></label>{!compact && <label><span>What can we help with?</span><textarea name="scope" required placeholder="Tell us about your project, partnership, or idea." rows={4} /></label>}<div className="privacy-note"><ShieldCheck /> Your details stay private. No spam.</div><button className="button button-primary button-wide" type="submit">{sent ? <><CheckCircle2 /> Opening your email</> : <>Send enquiry <ArrowUpRight /></>}</button></form>;
}

type Mode = "signin" | "signup";
export function AuthDock() {
  const [open,setOpen]=useState(false); const [mode,setMode]=useState<Mode>("signin"); const [user,setUser]=useState<User|null>(null); const [loading,setLoading]=useState(true); const [working,setWorking]=useState(false); const [message,setMessage]=useState<{type:"error"|"success";text:string}|null>(null);
  useEffect(()=>{ const supabase=getSupabase(); if(!supabase){setLoading(false);return;} supabase.auth.getSession().then(({data})=>{setUser(data.session?.user??null);setLoading(false);}); const {data}=supabase.auth.onAuthStateChange((_event,session)=>{setUser(session?.user??null);setLoading(false);}); return()=>data.subscription.unsubscribe(); },[]);
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setMessage(null);const supabase=getSupabase();if(!supabase){setMessage({type:"error",text:"Member access is awaiting the DevQuest Supabase keys."});return;}const data=new FormData(event.currentTarget);const email=String(data.get("email")||"").trim();const password=String(data.get("password")||"");const fullName=String(data.get("fullName")||"").trim();setWorking(true);if(mode==="signin"){const {error}=await supabase.auth.signInWithPassword({email,password});setWorking(false);setMessage(error?{type:"error",text:error.message}:{type:"success",text:"Welcome back to DevQuest."});return;}const {data:created,error}=await supabase.auth.signUp({email,password,options:{data:{full_name:fullName}}});setWorking(false);setMessage(error?{type:"error",text:error.message}:{type:"success",text:created.session?"Your DevQuest account is ready.":"Check your email to confirm your DevQuest account."});}
  async function signOut(){const supabase=getSupabase();if(!supabase)return;setWorking(true);const {error}=await supabase.auth.signOut();setWorking(false);if(error)setMessage({type:"error",text:error.message});else{setUser(null);setMessage({type:"success",text:"You are signed out."});}}
  const name=user?.user_metadata?.full_name||user?.email?.split("@")[0]||"Member";
  return <div className={`auth-dock ${open?"is-open":""}`}>{open&&<section className="auth-popup" role="dialog" aria-label="DevQuest member access"><button className="auth-close" type="button" onClick={()=>setOpen(false)} aria-label="Close member access"><X /></button><div className="auth-popup-head"><span><UserRound /></span><div><small>DEVQUEST ACCOUNT</small><h2>{user?`Welcome, ${name}`:mode==="signin"?"Welcome back.":"Join the quest."}</h2></div></div>{loading?<div className="auth-loading"><LoaderCircle /> Checking your session…</div>:user?<div className="auth-account"><div className="auth-user-row"><span>{name.slice(0,2).toUpperCase()}</span><div><strong>{name}</strong><small>{user.email}</small></div></div><p>Your DevQuest session is active on this device.</p>{message&&<Status {...message}/>}<button className="button auth-signout" type="button" onClick={signOut} disabled={working}>{working?<LoaderCircle className="spin"/>:<LogOut/>} Sign out</button></div>:<><div className="auth-tabs"><button type="button" className={mode==="signin"?"active":""} onClick={()=>{setMode("signin");setMessage(null);}}><LogIn/> Sign in</button><button type="button" className={mode==="signup"?"active":""} onClick={()=>{setMode("signup");setMessage(null);}}><UserPlus/> Create account</button></div><form className="auth-form" onSubmit={submit}>{mode==="signup"&&<label><span>Full name</span><div><UserRound/><input name="fullName" required placeholder="Your name" autoComplete="name"/></div></label>}<label><span>Email address</span><div><Mail/><input name="email" type="email" required placeholder="you@example.com" autoComplete="email"/></div></label><label><span>Password</span><div><LockKeyhole/><input name="password" type="password" required minLength={8} placeholder="Minimum 8 characters" autoComplete={mode==="signin"?"current-password":"new-password"}/></div></label>{message&&<Status {...message}/>}<button className="button button-primary button-wide" type="submit" disabled={working}>{working?<><LoaderCircle className="spin"/> Please wait</>:mode==="signin"?<>Sign in <LogIn/></>:<>Create DevQuest account <UserPlus/></>}</button></form><p className="auth-note">Authentication is managed by DevQuest through its own Supabase project. No ChatGPT login is used.</p></>}</section>}<button className="auth-trigger" type="button" onClick={()=>setOpen(v=>!v)} aria-expanded={open}>{user?<span>{name.slice(0,2).toUpperCase()}</span>:<UserRound/>}<strong>{user?"My account":"Member access"}</strong></button></div>;
}

function Status({type,text}:{type:"error"|"success";text:string}){return <div className={`auth-status ${type}`}>{type==="success"?<CheckCircle2/>:<AlertCircle/>}{text}</div>;}
