"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";
import Link from "next/link";
import type { User } from "@supabase/supabase-js";
import { AlertCircle, ArrowLeft, BarChart3, CalendarCheck2, CheckCircle2, Circle, ClipboardList, KeyRound, LayoutDashboard, LoaderCircle, LogOut, Plus, ShieldCheck, Trash2, UserCog, UsersRound } from "lucide-react";
import { getSupabaseBrowserClient, isSupabaseConfigured } from "../../lib/supabase-browser";

type Tab = "overview" | "members" | "tasks" | "attendance" | "reports";
type Member = { id: string; email?: string; full_name?: string | null; role?: "member" | "ambassador" | "team" | "admin"; department?: string | null; job_title?: string | null; is_active?: boolean; lastSignInAt?: string | null };
type Task = { id: string; title: string; description: string | null; assignee_id: string | null; assignee_name: string | null; priority: "low" | "medium" | "high"; status: "todo" | "in_progress" | "completed"; due_date: string | null };
type Attendance = { id: string; user_id: string; attendance_date: string; check_in: string | null; check_out: string | null; status: string };
type Report = { id: string; user_id: string; report_type: string; summary: string; blockers: string | null; submitted_at: string };

const nav = [
  { id: "overview" as const, label: "Overview", icon: LayoutDashboard },
  { id: "members" as const, label: "Team & credentials", icon: UsersRound },
  { id: "tasks" as const, label: "Task management", icon: ClipboardList },
  { id: "attendance" as const, label: "Attendance", icon: CalendarCheck2 },
  { id: "reports" as const, label: "Reports", icon: BarChart3 },
];
const fmt = (value?: string | null) => value ? new Intl.DateTimeFormat("en-PK", { day: "numeric", month: "short", year: "numeric", hour: "numeric", minute: "2-digit" }).format(new Date(value)) : "—";

export function AdminPortal() {
  const [tab, setTab] = useState<Tab>("overview"); const [user, setUser] = useState<User | null>(null); const [isAdmin, setIsAdmin] = useState(false);
  const [members, setMembers] = useState<Member[]>([]); const [tasks, setTasks] = useState<Task[]>([]); const [attendance, setAttendance] = useState<Attendance[]>([]); const [reports, setReports] = useState<Report[]>([]);
  const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [message, setMessage] = useState<{ type: "error" | "success"; text: string } | null>(null);
  const supabase = getSupabaseBrowserClient();

  const api = useCallback(async (method: string, body?: unknown) => {
    if (!supabase) throw new Error("Supabase is not configured."); const { data } = await supabase.auth.getSession(); const token = data.session?.access_token;
    const response = await fetch("/api/admin/members", { method, headers: { "Content-Type": "application/json", Authorization: `Bearer ${token}` }, body: body ? JSON.stringify(body) : undefined });
    const result = await response.json(); if (!response.ok) throw new Error(result.error || "Admin request failed"); return result;
  }, [supabase]);

  const refresh = useCallback(async (activeUser: User) => {
    if (!supabase) return;
    const { data: profile } = await supabase.from("profiles").select("role").eq("id", activeUser.id).single();
    if (profile?.role !== "admin") { setIsAdmin(false); return; } setIsAdmin(true);
    const [memberResult, taskResult, attendanceResult, reportResult] = await Promise.all([api("GET"), supabase.from("team_tasks").select("*").order("created_at", { ascending: false }), supabase.from("team_attendance").select("*").order("attendance_date", { ascending: false }).limit(250), supabase.from("team_reports").select("*").order("submitted_at", { ascending: false }).limit(250)]);
    setMembers(memberResult.members ?? []); if (!taskResult.error) setTasks((taskResult.data ?? []) as Task[]); if (!attendanceResult.error) setAttendance((attendanceResult.data ?? []) as Attendance[]); if (!reportResult.error) setReports((reportResult.data ?? []) as Report[]);
  }, [api, supabase]);

  useEffect(() => { if (!supabase) { queueMicrotask(() => setLoading(false)); return; } supabase.auth.getSession().then(async ({ data }) => { const active = data.session?.user ?? null; setUser(active); if (active) await refresh(active); setLoading(false); }); }, [refresh, supabase]);

  async function createMember(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = event.currentTarget; const values = new FormData(form); setSaving(true); setMessage(null); try { const result = await api("POST", Object.fromEntries(values)); setMessage({ type: "success", text: result.message }); form.reset(); if (user) await refresh(user); } catch (error) { setMessage({ type: "error", text: error instanceof Error ? error.message : "Could not create member" }); } finally { setSaving(false); } }
  async function updateMember(id: string, changes: Record<string, unknown>) { setSaving(true); setMessage(null); try { const result = await api("PATCH", { id, ...changes }); setMessage({ type: "success", text: result.message }); if (user) await refresh(user); } catch (error) { setMessage({ type: "error", text: error instanceof Error ? error.message : "Could not update member" }); } finally { setSaving(false); } }
  async function createTask(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!supabase || !user) return; const form = event.currentTarget; const values = new FormData(form); const assignee = members.find((member) => member.id === values.get("assigneeId")); setSaving(true); const { error } = await supabase.from("team_tasks").insert({ title: values.get("title"), description: values.get("description") || null, assignee_id: assignee?.id || null, assignee_name: assignee?.full_name || assignee?.email || null, priority: values.get("priority"), due_date: values.get("dueDate") || null, created_by: user.id }); setSaving(false); if (error) setMessage({ type: "error", text: error.message }); else { form.reset(); setMessage({ type: "success", text: "Task assigned." }); await refresh(user); } }
  async function deleteTask(id: string) { if (!supabase || !user || !window.confirm("Delete this task?")) return; setSaving(true); const { error } = await supabase.from("team_tasks").delete().eq("id", id); setSaving(false); if (error) setMessage({ type: "error", text: error.message }); else await refresh(user); }
  async function signOut() { if (!supabase) return; setSaving(true); setMessage(null); const { error } = await supabase.auth.signOut({ scope: "global" }); if (error) { setSaving(false); setMessage({ type: "error", text: error.message }); return; } window.location.replace("/portal#member-signin"); }

  if (loading) return <State title="Opening Admin Portal" copy="Verifying administrator access…" />;
  if (!isSupabaseConfigured()) return <State title="Configuration required" copy="Supabase environment variables are missing." />;
  if (!user) return <State title="Sign in as an administrator" copy="Use your approved DevQuest admin credentials." action={<a href="#member-signin"><KeyRound /> Open portal login</a>} />;
  if (!isAdmin) return <State title="Administrator access required" copy="This account does not have permission to enter the Admin Portal." />;
  const memberName = (id: string) => members.find((member) => member.id === id)?.full_name || members.find((member) => member.id === id)?.email || "Unknown member";
  return <div className="team-portal-shell admin-portal-shell"><aside className="team-portal-sidebar"><Link className="team-portal-wordmark" href="/portal"><span>DQ</span><b>Admin<br />Portal</b></Link><nav>{nav.map(({ id, label, icon: Icon }) => <button key={id} className={tab === id ? "active" : ""} onClick={() => setTab(id)} title={label}><Icon /> {label}</button>)}</nav><div className="team-portal-user"><span>AD</span><div><b>Administrator</b><small>{user.email}</small></div></div></aside><main className="team-portal-main"><header className="team-portal-topbar"><div><p>DEVQUEST OPERATIONS</p><h1>{nav.find((item) => item.id === tab)?.label}</h1></div><div className="team-portal-account-actions"><div className="team-portal-top-user"><span>AD</span><div><b>Administrator</b><small>{user.email}</small></div></div><button className="portal-signout" type="button" onClick={signOut} disabled={saving} aria-label="Sign out of Admin Portal">{saving ? <LoaderCircle className="spin" /> : <LogOut />}<span>Sign out</span></button></div></header>{message && <div className={`portal-message ${message.type}`}>{message.type === "success" ? <CheckCircle2 /> : <AlertCircle />}{message.text}</div>}
    {tab === "overview" && <Overview members={members} tasks={tasks} attendance={attendance} reports={reports} setTab={setTab} />}
    {tab === "members" && <Members members={members} saving={saving} onCreate={createMember} onUpdate={updateMember} />}
    {tab === "tasks" && <Tasks members={members} tasks={tasks} saving={saving} onCreate={createTask} onDelete={deleteTask} />}
    {tab === "attendance" && <section className="portal-panel portal-work-grid"><Head kicker="TEAM RECORD" title="Attendance overview" /><div className="admin-table"><div className="admin-table-row admin-table-head"><span>Member</span><span>Date</span><span>Check in</span><span>Check out</span><span>Status</span></div>{attendance.map((entry) => <div className="admin-table-row" key={entry.id}><b>{memberName(entry.user_id)}</b><span>{entry.attendance_date}</span><span>{fmt(entry.check_in)}</span><span>{fmt(entry.check_out)}</span><span>{entry.status}</span></div>)}{!attendance.length && <Empty text="No attendance records yet." />}</div></section>}
    {tab === "reports" && <section className="portal-panel portal-work-grid"><Head kicker="TEAM OUTPUT" title="Submitted reports" /><div className="portal-report-list">{reports.map((report) => <article key={report.id}><span><BarChart3 /></span><div><div><b>{memberName(report.user_id)} · {report.report_type}</b><small>{fmt(report.submitted_at)}</small></div><p>{report.summary}</p>{report.blockers && <em>Blocker: {report.blockers}</em>}</div></article>)}{!reports.length && <Empty text="No reports submitted yet." />}</div></section>}
  </main></div>;
}

function State({ title, copy, action }: { title: string; copy: string; action?: React.ReactNode }) { return <div className="portal-state"><section><Link className="portal-back" href="/portal"><ArrowLeft /> All portals</Link><div className="portal-state-icon"><ShieldCheck /></div><p className="portal-kicker">ADMIN PORTAL</p><h1>{title}</h1><p>{copy}</p>{action && <div className="portal-state-action">{action}</div>}</section></div>; }
function Head({ kicker, title }: { kicker: string; title: string }) { return <div className="portal-panel-head"><div><p>{kicker}</p><h2>{title}</h2></div></div>; }
function Overview({ members, tasks, attendance, reports, setTab }: { members: Member[]; tasks: Task[]; attendance: Attendance[]; reports: Report[]; setTab: (tab: Tab) => void }) { const stats = [["Team accounts", members.filter((m) => m.role === "team").length, UsersRound, "blue"], ["Open tasks", tasks.filter((t) => t.status !== "completed").length, ClipboardList, "gold"], ["Attendance entries", attendance.length, CalendarCheck2, "green"], ["Reports", reports.length, BarChart3, "purple"]] as const; return <div className="portal-dashboard"><section className="portal-welcome"><div><p>ADMINISTRATION</p><h2>Everything your DevQuest team needs to keep moving.</h2><span>One administrator manages every individual team workspace.</span></div><button onClick={() => setTab("members")}>Manage members</button></section><div className="portal-stat-grid">{stats.map(([label, value, Icon, tone]) => <article className={`portal-stat ${tone}`} key={label}><span><Icon /></span><div><strong>{value}</strong><p>{label}</p></div></article>)}</div></div>; }
function Members({ members, saving, onCreate, onUpdate }: { members: Member[]; saving: boolean; onCreate: (e: FormEvent<HTMLFormElement>) => void; onUpdate: (id: string, changes: Record<string, unknown>) => void }) { const teamMembers = members.filter((member) => member.role === "team"); return <div className="portal-work-grid admin-members-layout"><section className="portal-panel"><Head kicker="NEW TEAM MEMBER" title="Create an individual portal" /><form className="portal-inline-form" onSubmit={onCreate}><label>Full name<input name="fullName" required /></label><label>Email<input name="email" type="email" required /></label><label>Temporary password<input name="password" type="password" minLength={8} required /></label><div className="portal-form-row"><label>Department<input name="department" /></label><label>Job title<input name="jobTitle" /></label></div><button className="portal-primary" disabled={saving}><Plus /> Create team portal</button></form><p className="portal-security-note"><ShieldCheck /> Every account receives its own isolated Team Portal. Passwords are stored only by Supabase Auth.</p></section><section className="portal-panel"><Head kicker="TEAM ACCESS" title="Individual team portals" /><div className="admin-member-list">{teamMembers.map((member) => <article key={member.id}><span><UserCog /></span><div><b>{member.full_name || "Unnamed member"}</b><small>{member.email}<br />{member.department || "No department"} · {member.job_title || "No title"}</small></div><button className="portal-mini-action" onClick={() => { const password = window.prompt(`New temporary password for ${member.email}`); if (password) void onUpdate(member.id, { password }); }}><KeyRound /> Reset password</button><button className="portal-mini-action" onClick={() => onUpdate(member.id, { isActive: member.is_active === false })}>{member.is_active === false ? "Activate" : "Disable"}</button></article>)}{!teamMembers.length && <Empty text="No team portals created yet." />}</div></section></div>; }
function Tasks({ members, tasks, saving, onCreate, onDelete }: { members: Member[]; tasks: Task[]; saving: boolean; onCreate: (e: FormEvent<HTMLFormElement>) => void; onDelete: (id: string) => void }) { return <div className="portal-work-grid admin-members-layout"><section className="portal-panel"><Head kicker="ASSIGNMENT" title="Create task" /><form className="portal-inline-form" onSubmit={onCreate}><label>Title<input name="title" required /></label><label>Assign to<select name="assigneeId" required defaultValue=""><option value="" disabled>Select team member</option>{members.filter((m) => m.role === "team").map((m) => <option value={m.id} key={m.id}>{m.full_name || m.email}</option>)}</select></label><div className="portal-form-row"><label>Priority<select name="priority"><option value="low">Low</option><option value="medium">Medium</option><option value="high">High</option></select></label><label>Due date<input name="dueDate" type="date" /></label></div><label>Details<textarea name="description" rows={4} /></label><button className="portal-primary" disabled={saving}><Plus /> Assign task</button></form></section><section className="portal-panel"><Head kicker="ALL ASSIGNMENTS" title="Task list" /><div className="portal-task-cards">{tasks.map((task) => <article key={task.id}><div className="portal-task-title"><span className={`task-dot ${task.status}`} /><div><h3>{task.title}</h3><p>{task.assignee_name || "Unassigned"} · {task.status.replace("_", " ")}</p></div><em className={`priority-${task.priority}`}>{task.priority}</em></div><div className="portal-task-meta"><span>{task.due_date || "No due date"}</span><button className="portal-icon-danger" onClick={() => onDelete(task.id)} disabled={saving} aria-label={`Delete ${task.title}`}><Trash2 /></button></div></article>)}{!tasks.length && <Empty text="No tasks created yet." />}</div></section></div>; }
function Empty({ text }: { text: string }) { return <div className="portal-empty"><Circle /> {text}</div>; }
